config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  devise_for :users
  root to: 'pages#home'
  get 'profile', to: 'pages#profile'
  get 'bookings', to: 'pages#bookings'
  get 'confirmation', to: 'pages#confirmation'


  resources :users do
    resources :bookings, only:[:new, :create, :update, :edit, :index] do
        resources :reviews, only:[:new, :create, :update, :edit, :index]
      end
  end
  
  resources :bookings, except: [:new, :create] do
    member do
      get "confirmation"
    end
  end

  resources :bookings, only:[:confirmation] do
    resources :services, only:[:index, :show] do
      member do 
        get "confirmation"
      end
    end
  end
  
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  
  resources :services, only:[:new, :create, :update, :edit, :index]
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  
  has_many :bookings
  has_many :services
  has_many :orders
  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def average_rating
    sum = 0 
    counter = 0 
    mechanic_bookings = Booking.select {|booking| booking.service.user == self }
    mechanic_bookings.each do |booking|
      if booking.reviews.present?
        sum += booking.reviews.first.rating
        counter += 1
      end
    end
    (sum.to_f / counter) if counter > 0
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :home, :show]

  include CloudinaryHelper 


  def home
  
  end

  def index
    @users = User.where(mechanic: true)
    if params[:search_by_service].present?
      @services = Service.where("repair_name ILIKE ?", "%#{params[:search_by_service]}%")
    else
      @services = Service.all
    end
  end

  def show
    @user = User.find(params[:id])
    @booking = Booking.new

    @markers = [{
      lat: @user.to_coordinates.first,
      lng: @user.to_coordinates.last,
      info_window: render_to_string(partial: "map_box", locals: { user: @user }),
      image_url: cl_image_path("yr7vbtkxxfrlwjbceesz.jpg")
    }]

    sum = 0 
    counter = 0 
    mechanic_bookings = Booking.select {|booking| booking.service.user == @user}
    mechanic_bookings.each do |booking|
      if booking.reviews.present?
        sum += booking.reviews.first.rating
        counter += 1
      end
    end
    @average_rating = (sum.to_f / counter) if counter > 0
  end

  def edit
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name)
  end
end

app/views/users/_map_box.html.erb
<% if user %>
  <p><%= user.location %></p>
  <p><%= user.mechanic? %></p>
<% else %>
<% end %>

app/views/users/index.html.erb
<!-- Mechanic cards -->
<div class="i-container">
  <h1 class="i-title">Here are services <br> matching '<%= params["search_by_service"] %>'</h1>
  <div class="i-main-wrapper">
    <ul class="i-cards">
      <% @services.each do |service| %>
        <li>
        <%= link_to user_path(service.user) do %>
        <div class="i-card">
          <% if service.user.photo.attached? %>
            <%= cl_image_tag service.user.photo.key, height: 240, width: 360, crop: :fill, :class => "i-image" %>
          <% else %>
            <img src="https://www.guildford-dragon.com/wp-content/uploads/2020/08/Bike-Bros-logo.png">
          <% end %>
          <div class="i-card-content">
            <h2 class="i-card-title"><%= service.user.company_name %>
              <% if service.user.insta_availability == true %>
                <i class="fas fa-bolt"></i>
              <% end %></h2> 
              <p class="i-card-text"><%= icon('fas', 'map-marker-alt') %></i> <%= service.user.location  %></p>
              <p class="i-card-text"><%= icon('fas', 'bicycle') %> <%= service.repair_name %> </p>
              <p class="i-card-text"><%= icon('fas', 'money-bill-wave') %> <%= humanized_money_with_symbol(service.price) %></p> 
              <div class="stars">
                <%= icon('fas', 'star', style: 'color: white')  * service.user.average_rating.to_i %><%= icon('far', 'star', style: 'color: white') * (5 - service.user.average_rating.to_i) %>
              </div>
          </div>
        </div>
        <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="s-container">
  <div class="card-show">
    <% if @user.photo.attached? %>
      <%= cl_image_tag @user.photo.key, height: 240, width: 360, :class => "s-image" %>
    <% else %>
      <img src="https://www.guildford-dragon.com/wp-content/uploads/2020/08/Bike-Bros-logo.png">
    <% end %>
    <div class="s-text-map-container">
      <div class="s-text-wrapper">
        <div class="card-content-show">  
          <h2 class="s-card-title"><%= @user.company_name %> </h2> 
          <p class="s-card-text"><i class="fas fa-map-marker-alt"></i> <%= @user.location %></p>
          <% @user.services.each do |service| %>
            <p class="s-card-text"><%= icon('fas', 'bicycle') %> <%= service.repair_name %> <%= icon('fas', 'money-bill-wave') %> <%= humanized_money_with_symbol(service.price) %></p>
          <% end %>
          <%= icon('fas', 'star', class:'star')  * @average_rating.to_i %><%= icon('far', 'star', class: 'star') * (5 - @average_rating.to_i) %>
        </div>
        <%= link_to "Book Now", new_user_booking_path(@user), class: "btn-show" %>
      </div>
      <div class="s-mapbox">
        <div id="map"
          style="width:100%; height: 100%;"
          data-marker="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>


    <div class="review-container">
      <h2>Reviews</h2>
      <div class="serach-suggest-container">
        <label for="search" class="input-field">
          <i class="fas fa-search"></i>
          <input id="search" placeholder="Search for reviews ..." type="text">
        </label>
        <div class="suggest">
          <span>experiance</span>
          <span>features</span>
          <span>value</span>
          <span>service</span>
          <span>replacement</span>
        </div>
      </div>
      
      <div class="cards_review">
        <div class="card_review">
          <div class="card-top">
            <div class="name">
              <div class="img one" alt="">LE</div>
                <p>Lrvis Eapi</p>
            </div>
            <div class="rate">
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
            </div>
          </div>
          
          <div class="card-content">
            <p>The service was on point, the mechanic provided an exceptional service - he knew very well how to grease my chain</p>
          </div>
          
          <div class="card-action">
            <span>13 August, 2021</span>
            <button class="btn">
              <i class="fas fa-external-link-alt"></i>
              Share
            </button>
          </div>
          
        </div>
        <div class="card_review">
          <div class="card-top">
            <div class="name">
              <div class="img">KR</div>
              <p>Kahul Reerthi</p>
            </div>
            <div class="rate">
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
            </div>
          </div>
          
          <div class="card-content">
            <p>A little bit expensive, but overall good experience</p>
          </div>
          
          <div class="card-action">
            <span>25 August, 2021</span>
            <button class="btn">
              <i class="fas fa-external-link-alt"></i>
              Share
            </button>
          </div>      
        </div>

        <div class="card_review">
          <div class="card-top">
            <div class="name">
              <div class="img">JA</div>
              <p>Jnne de Aoly</p>
            </div>
            <div class="rate">
              <i class="fas fa-star"></i>
            </div>
          </div>
          
          <div class="card-content">
            <p>The French do it better...</p>
          </div>
          
          <div class="card-action">
            <span>1 September, 2021</span>
            <button class="btn">
              <i class="fas fa-external-link-alt"></i>
              Share
            </button>
          </div>      
        </div>
      </div>
    </div>
</div>