config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  devise_for :users
  root to: 'pages#home'
  get 'profile', to: 'pages#profile'
  get 'bookings', to: 'pages#bookings'
  get 'confirmation', to: 'pages#confirmation'


  resources :users do
    resources :bookings, only:[:new, :create, :update, :edit, :index] do
        resources :reviews, only:[:new, :create, :update, :edit, :index]
      end
  end
  
  resources :bookings, except: [:new, :create] do
    member do
      get "confirmation"
    end
  end

  resources :bookings, only:[:confirmation] do
    resources :services, only:[:index, :show] do
      member do 
        get "confirmation"
      end
    end
  end
  
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  
  resources :services, only:[:new, :create, :update, :edit, :index]
  
end

app/views/shared/_bottombar.html.erb
<% if user_signed_in? %>
<nav class="mobile-bottom-nav">
	<div class="mobile-bottom-nav__item">
		<div class="mobile-bottom-nav__item-content">
			<i class="fas fa-search fa-2x"></i>
      <%= link_to "Home", root_path  %>
		</div>		
	</div>
	<div class="mobile-bottom-nav__item">		
		<div class="mobile-bottom-nav__item-content">
			<i class="fas fa-user fa-2x"></i>
      <%= link_to "Profile", profile_path %>
		</div>
	</div>
	<div class="mobile-bottom-nav__item">
		<div class="mobile-bottom-nav__item-content">
			<i class="fas fa-wrench fa-2x"></i>
      <%= link_to "Bookings", bookings_path %>
		</div>		
	</div>
</nav>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="new_footer_area bg_color">
  <div class="new_footer_top">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6">
          <div class="f_widget company_widget wow fadeInLeft" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInLeft;">
            <h3 class="f-title f_600 t_color f_size_18">Get in Touch</h3>
            <p>Don’t miss any updates!</p>
            <form action="#" class="f_subscribe_two mailchimp" method="post" novalidate="true" _lpchecked="1">
              <input type="text" name="EMAIL" class="form-control memail" placeholder="Email">
              <button class="btn btn_get btn_get_two" type="submit">Subscribe</button>
              <p class="mchimp-errmessage" style="display: none;"></p>
              <p class="mchimp-sucmessage" style="display: none;"></p>
            </form>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="f_widget about-widget pl_70 wow fadeInLeft" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInLeft;">
            <h3 class="f-title f_600 t_color f_size_18">About Us</h3>
            <ul class="list-unstyled f_list">
              <li><a href="#">Company</a></li>
              <li><a href="#">Mission</a></li>
              <li><a href="#">Career</a></li>
              <li><a href="#">Team</a></li>
              <li><a href="#">Projects</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="f_widget about-widget pl_70 wow fadeInLeft" data-wow-delay="0.6s" style="visibility: visible; animation-delay: 0.6s; animation-name: fadeInLeft;">
            <h3 class="f-title f_600 t_color f_size_18">Help</h3>
            <ul class="list-unstyled f_list">
                <li><a href="#">FAQ</a></li>
                <li><a href="#">Term &amp; conditions</a></li>
                <li><a href="#">Documentation</a></li>
                <li><a href="#">Support Policy</a></li>
                <li><a href="#">Privacy</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="f_widget social-widget pl_70 wow fadeInLeft" data-wow-delay="0.8s" style="visibility: visible; animation-delay: 0.8s; animation-name: fadeInLeft;">
            <h3 class="f-title f_600 t_color f_size_18">Follow us on</h3>
            <div class="f_social_icon">
              <a href="#" class="fab fa-facebook"></a>
              <a href="#" class="fab fa-twitter"></a>
              <a href="#" class="fab fa-linkedin"></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer_bg">
      <div class="footer_bg_one"></div>
      <div class="footer_bg_two"></div>
      <div class="footer_bg_three"></div>
      <div class="footer_bg_four"></div>
    </div>
    </div>
    <div class="footer_bottom">
  </div>
</footer>

app/views/shared/_navbar.html.erb
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<nav id="navbar" class="">
  <div class="nav-wrapper">
    <!-- Navbar Logo -->
    <%= link_to root_path do %>
    <div class="logo">

      <!-- Logo Placeholder for Inlustration -->
      <% if user_signed_in? %>
        <% if current_user.mechanic == true %>
          <i id='bikeimage' class="fa-solid fa-wrench"></i> Bike Fix</a>
        <% elsif current_user.mechanic == false %>
          <i id='bikeimage' class="fa-solid fa-person-biking"></i> Bike Fix</a>
        <% else %>
        <i class="fas fa-bicycle"></i> Bike Fix</a>
        <% end %>
      <% else %>
        <i id='bikeimage_out' class="fas fa-bicycle"></i> Bike Fix</a>
      <% end %>
    </div>
    <% end %>

    <!-- Navbar Links -->
    <ul id="menu">
      <% if user_signed_in? %>
        <li><%= link_to "Home", root_path  %></li>
        <li><%= link_to "Profile", profile_path %></li>
        <li><%= link_to "Bookings", bookings_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => "delete"  %>
        <% else %>
        <li><%= link_to "Home", root_path  %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

<!-- Menu Icon -->
<div class="menuIcon">
  <span class="icon icon-bars"></span>
</div>

<div class="overlay-menu">
  <ul id="menu">
    <% if user_signed_in? %>
      <li><%= link_to "Home", root_path  %></li>
      <li><%= link_to "Profile", profile_path %></li>
      <li><%= link_to "Bookings", bookings_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, :method => "delete"  %>
      <% else %>
      <li><%= link_to "Home", root_path  %></li>
      <li><%= link_to "Sign In", new_user_session_path %></li>
    <% end %>
  </ul>
</div>